import json

# with open('translations.json', 'r') as fp:
#     translations = json.load(fp)

translations = {
    "MainMenuCollection": {"Hrvatski": "Zbirke", "English": "Collections"},
    "MainMenuModels": {"Hrvatski": "Modeli", "English": "Models"},
    "MainMenuCitationStyles": {"Hrvatski": "Citatni stilovi", "English": "Citation styles"},
    "MainMenuMappings": {"Hrvatski": "Mapiranja", "English": "Mappings"},
    "MainMenuSettings": {"Hrvatski": "Postavke", "English": "Settings"},
    "MainMenuHelp": {"Hrvatski": "Pomoć", "English": "Help"},
    "MainMenuModelsNewModel": {"Hrvatski": "Izrada novog modela", "English": "Create new model"},
    "MainMenuModelsCopyModel": {"Hrvatski": "Izrada novog modela iz postojećeg modela", "English": "Create new model from existing model"},
    "MainMenuModelsChooseDefaultModel": {"Hrvatski": "Odaberi zadani model", "English": "Choose default model"},
    "MainMenuCollectionNewCollection": {"Hrvatski": "Nova zbirka", "English": "New collection"},
    "MainMenuCollectionEditCollection": {"Hrvatski": "Otvori zbirku", "English": "Open collection"},
    "MainMenuCitationStylesNewCitationStyle": {"Hrvatski": "Novi citatni stil", "English": "New citation style"},
    "MainMenuCitationStylesEditCitationStyle": {"Hrvatski": "Uredi postojeći citatni stil", "English": "Edit existing citation style"},
    "MainMenuCitationStylesChooseDefaultStyle": {"Hrvatski": "Odaberi zadani citatni stil", "English": "Choose default citation style"},
    "MainMenuMappingsFormats": {"Hrvatski": "Mapiranje formata", "English": "Map formats"},
    "MainMenuMappingsCitationStyles": {"Hrvatski": "Mapiranje citatnih stilova", "English": "Map citation styles"},
    "MainMenuSettingsEditAppereance": {"Hrvatski": "Izgled", "English": "Appereance"},
    "MainMenuSettingsChooseLanguage": {"Hrvatski": "Odabir jezika sučelja", "English": "Choose GUI language"},
    "MainMenuSettingsAddLanguage": {"Hrvatski": "Dodavanje jezika sučelja", "English": "Add GUI language"},
    "NewModelWindowTitle": {"Hrvatski": "Izrada novog modela", "English": "Create new model"},
    "NewModelWindowFieldNamePlaceholder": {"Hrvatski": "Ime polja", "English": "Field name"},
    "NewModelWindowFieldLabelPlaceholder": {"Hrvatski": "Naziv polja", "English": "Field label"},
    "NewModelWindowAddField": {"Hrvatski": "Dodaj polje", "English": "Add a field"},
    "NewModelWindowFieldTypeInteger": {"Hrvatski": "Cijeli broj", "English": "Integer"},
    "NewModelWindowFieldTypeString": {"Hrvatski": "Tekst", "English": "String"},
    "True": {"Hrvatski": "Da", "English": "True"},
    "False": {"Hrvatski": "Ne", "English": "False"},
    "NewModelWindowIsManyLabel": {"Hrvatski": "Više vrijednosti?", "English": "Multi values?"},
    "NewModelWindowTypeLabel": {"Hrvatski": "Vrsta polja", "English": "Field type"},
    "NewModelWindowAddType": {"Hrvatski": "Dodaj vrstu publikacije", "English": "Add type of publication"},
    "NewModelTypeName": {"Hrvatski": "Ime vrste publikacije", "English": "Type of publication name"},
    "NewModelTypeLabel": {"Hrvatski": "Naziv vrste publikacije", "English": "Type of publication label"},
    "NewModelTypeMandatoryFields": {"Hrvatski": "Obvezna polja", "English": "Mandatory fields"},
    "NewModelTypeOptionalFields": {"Hrvatski": "Neobvezna polja", "English": "Optional fields"},
    "NewModelWindowSeperatedByCommas": {"Hrvatski": "Imena polja odvojiti zarezom", "English": "Field names seperated by commas"},
    "NewModelWindowFinalizeModel": {"Hrvatski": "Izradi model", "English": "Create model"},
    "NewModelWindowModelName": {"Hrvatski": "Naziv modela", "English": "Model name"},
    "MainMenuChooseDefaultModelIsDefault": {"Hrvatski": "(zadani model)", "English": "(default model)"},
    "OKDialogTitle": {"Hrvatski": "Obavijest", "English": "Info"},
    "SettingDefaultRestartApp": {"Hrvatski": "Zadani model bit će postavljen pri ponovnom pokretanju programa.", "English":"The default model will be set on app restart."},
    "OKButtonUniversal": {"Hrvatski": "U redu", "English": "OK"},
    "LoadedStatusInfo": {"Hrvatski": "učitan", "English": "loaded"},
    "LoadedModelsInfo": {"Hrvatski": "Učitanih modela: ", "English": "Loaded models: "},
    "DefaultModelInfo": {"Hrvatski": "Zadani model: ", "English": "Default model: "},
    "GroupButton": {"Hrvatski": "Grupiranje", "English": "Group"},
    "FilterButton": {"Hrvatski": "Filtriranje", "English": "Filter"},
    "PrepareItemsButton": {"Hrvatski": "Priprema zapisa", "English": "Prepare items"},
    "ImportFromFilesButton": {"Hrvatski": "Uvoz zapisa", "English": "Import items"},
    "AddItemButton": {"Hrvatski": "Dodaj zapis", "English": "Add item"},
    "SaveCollectionState": {"Hrvatski": "Spremi stanje zbirke", "English": "Save collection state"},
    "LoadCollectionState": {"Hrvatski": "Prethodna stanja zbirke", "English": "Previous collection states"},
    "EditCollectionView": {"Hrvatski": "Uredi prikazivanje zapisa", "English": "Edit collection view"},
    "TrashBin": {"Hrvatski": "Koš za smeće", "English": "Recycle Bin"},
    "MainMenuCollectionSaveCollection": {"Hrvatski": "Spremi zbirku", "English": "Save collection"},
    "": {"Hrvatski": "", "English": ""},
    "AllModelsPanelText": {"Hrvatski": "Ukupno modela", "English": "Models defined"},
    "DefaultModelMandatoryText": {"Hrvatski": "obvezno polje", "English": "mandatory"},
    "CollectionsPreviewLastCollection": {"Hrvatski": "Posljednja zbirka", "English": "Latest collection"},
    "AddNewItemWindowTitle": {"Hrvatski": "Novi zapis", "English": "New item"},
    "AddNewItemWindowHeading": {"Hrvatski": "Ručno dodavanja zapisa", "English": "Add item manually"},
    "AddNewItemWindowText": {"Hrvatski": "Odaberite vrstu publikacije.<br>Obvezna polja označena su podebljanim slovima.<br>Polja koja dopuštaju više vrijednosti označena su ukošenim slovima.", "English": "Choose the type of publication.<br>Required fields are bolded.<br>Fields that support multiple values are italicazed."},
    "AddItemToCollectionExecuteButton": {"Hrvatski": "Dodaj u zbirku", "English":"Add to collection"},
    "SeperateValuesWithNewLine": {"Hrvatski": "(vrijednosti odvojiti novim redom)", "English": "(seperate values by new line)"},
    "FieldsAreRequiredWarning": {"Hrvatski": "Obvezna polja ({}) nisu ispunjena!", "English": "Required fields ({}) are missing!"},
    "IntegerType": {"Hrvatski": "(broj)", "English": "(number)"},
    "InvalidFieldsWarning": {"Hrvatski": "Polja ({}) nisu valjana", "English": "Fields ({}) are not valid"},
    "EditItemButton": {"Hrvatski": "Uredi zapis", "English": "Edit item"},
    "EditColViewWindowTitle": {"Hrvatski": "Prikazivanje zapisa", "English": "Collection View Settings"},
    "ChooseForCollectionView": {"Hrvatski": "Primjeni", "English": "Apply"},
    "GroupingWindowTitle": {"Hrvatski": "Grupiranje zapisa", "English": "Item grouping"},
    "GroupingLevel": {"Hrvatski": "Razina grupiranja", "English": "Grouping level"},
    "AddGroupingLevelButton": {"Hrvatski": "Dodaj razinu", "English": "Add grouping level"},
    "ClearGroupingLevels": {"Hrvatski": "Poništi sve", "English": "Clear all grouping parameters"},
    "GroupingOptions": {"Hrvatski": "Mogućnosti grupiranja", "English": "Grouping options"},
    "ApplyGroupingParams": {"Hrvatski": "Primjeni grupiranje na zbirku", "English": "Apply grouping parameters to collection"},
    "AppereanceWindowTitle": {"Hrvatski": "Izgled sučelja", "English": "Interface Appereance"},
    "AppereanceWindowChooseThemeLabel": {"Hrvatski": "Odabir teme za prikaz sučelja", "English": "Choose interface theme"},
    "ApplyGeneral": {"Hrvatski": "Primjeni", "English": "Apply"},
    "ChooseColorButton": {"Hrvatski": "Odaberi boju", "English": "Pick color"},
    "BackgroundColor": {"Hrvatski": "Pozadinska boja", "English": "Background color"},
    "ForegroundColor": {"Hrvatski": "Prednja boja/boja teksta", "English": "Foreground color"},
    "HighlightColor": {"Hrvatski": "Istaknuta boja", "English": "Highlight color"},
    "HighlightedTextColor": {"Hrvatski": "Boja istaknutog teksta", "English": "Highlighted text color"},
    "BorderColor": {"Hrvatski": "Boja rubova", "English": "Border color"},
    "AccentColor": {"Hrvatski": "Naglašena boja", "English": "Accent color"},
    "WarningColor": {"Hrvatski": "Boja upozorenja", "English": "Warning color"},
    "PreviewNewTheme": {"Hrvatski": "Pretpregled", "English": "Preview"},
    "AddNewThemeButton": {"Hrvatski": "Dodaj novu temu", "English": "Add new theme"},
    "AddAndApplyNewTheme": {"Hrvatski": "Dodaj i primjeni novu temu", "English": "Add and apply new theme"},
    "NewThemeNameTextBox": {"Hrvatski": "Naziv nove teme", "English": "New theme name"},
    "RemoveSelectedItemsButton": {"Hrvatski": "Izbriši sve odabrane zapise", "English": "Delete all selected items"},
    "RemoveItemButton": {"Hrvatski": "Izbriši zapis", "English": "Delete item"},
    "RecycleBinWindowTitle": {"Hrvatski": "Koš za smeće", "English": "Recycle Bin"},
    "PermaDeleteAllButton": {"Hrvatski": "Trajno izbriši sve zapise", "English": "Permanently delete all items"},
    "PermaDeleteSelectedButton": {"Hrvatski": "Trajno izbriši označene zapise", "English": "Permanently delete selected items"},
    "RestoreAllButton": {"Hrvatski": "Vrati sve zapise u zbirku", "English": "Restore all items to collection"},
    "RestoreSelectedButton": {"Hrvatski": "Vrati označene zapise u zbirku", "English": "Restore selected items to collection"},
    "PermaDeleteButton": {"Hrvatski": "Trajno izbriši", "English": "Permanently delete"},
    "RestoreButton": {"Hrvatski": "Vrati u zbirku", "English": "Restore item"},
    "RecycleBinEmptyLabel": {"Hrvatski": "Nema izbrisanih zapisa", "English": "Recycle Bin is empty"},
    "CSVWindowTitle": {"Hrvatski": "CSV mapiranje", "English": "CSV mapping"},
    "NewCSVMapperButton": {"Hrvatski": "Novo mapiranje za ovaj model", "English": "New mapping for this model"},
    "DelimiterLabel": {"Hrvatski": "Graničnik", "English": "Delimiter"},
    "CSVMapperName": {"Hrvatski": "Naziv CSV mapiranja", "English": "CSV mapper name"},
    "CSVFieldsLabel": {"Hrvatski": "Mapiranja CSV polja", "English": "CSV field mappers"},
    "CSVAddFieldButton": {"Hrvatski": "Dodaj polje", "English": "Add field"},
    "CSVTypesLabel": {"Hrvatski": "Mapiranja CSV vrsti publikacija", "English": "CSV publication type mappers"},
    "CSVAddTypeButton": {"Hrvatski": "Dodaj vrstu publikacije", "English": "Add publication type"},
    "CSVAddFieldsFromFileButton": {"Hrvatski": "Dodaj polja iz CSV datoteke", "English": "Add fields from CSV file"},
    "CSVSaveChangesButton": {"Hrvatski": "Spremi promjene", "English": "Save changes"},
    "NewCSVTabTitle": {"Hrvatski": "Novo mapiranje", "English":"New mapping"},
    "CSVMappingEditButton": {"Hrvatski": "Uredi mapiranje", "English": "Edit mapping"},
    "CSVMappingDeleteButton": {"Hrvatski": "Ukloni mapiranje", "English": "Remove mapping"},
    "CSVAddMapperForModel": {"Hrvatski": "Novo mapiranje za ovaj model", "English": "New mapping for this model"},
    "CSVNoMappingsLabel": {"Hrvatski": "Nema definiranih mapiranja za ovaj model", "English": "No mappings defined for this model"},
    "CSVFieldPlaceholder": {"Hrvatski": "CSV polje", "English": "CSV field"},
    "CSVTypePlaceholder": {"Hrvatski": "CSV vrsta publikacije", "English": "CSV publication type"},
    "CSVMapAllToOneType": {"Hrvatski": "Mapiraj sve zapise u jednu vrstu publikacije", "English": "Map all items to one type of publication"},
    "CSVReadFromFileError": {"Hrvatski": "Pogreška pri učitavanju datoteke", "English": "Error reading the file"},
    "CSVTabDelimitedBox": {"Hrvatski": "Razgraničen tabulatorom", "English": "Tab delimited"},
    "CSVDelimiterPlaceholder": {"Hrvatski": "Ostaviti prazno ako je graničnik tabulator", "English": "Leave empty if tab delimited"},
    "UniversalImportWindowTitle": {"Hrvatski": "Uvoz zapisa", "English": "Import items from files"},
    "ValidateOnImport": {"Hrvatski": "Provjera valjanosti zapisa pri uvozu", "English": "Validate items on import"},
    "ChooseFilesForImport": {"Hrvatski": "Odabir datoteka za uvoz", "English": "Choose files for import"},
    "TransformOnImport": {"Hrvatski": "Transformacija vrijednosti pri uvozu", "English": "Transform values on import"},
    "ImportFilesButton": {"Hrvatski": "Izvrši uvoz", "English": "Execute import"},
    "UnknownFormatLabel": {"Hrvatski": "Nepoznati format", "English": "Unknown format"},
    "ImportErrorReportWindowTitle": {"Hrvatski": "Izvještaj o neispravnim zapisima", "English": "Invalid items report"},
    "ImportErrorReportSummaryTitle": {"Hrvatski": "Brzi pregled", "English": "At a glance"},
    "TotalNumberOfInvalidItems": {"Hrvatski": "Ukupan broj nevaljalih zapisa", "English": "Total no. of invalid items"},
    "TotalMissingLabel": {"Hrvatski": "Ukupan broj neispunjenih obveznih polja", "English": "Total no. of empty mandatory fields"},
    "TotalFaultyLabel": {"Hrvatski": "Ukupan broj nepravilnih vrijednosti polja", "English": "Total no. of invalid field values"},
    "MissingFieldsLabel": {"Hrvatski": "Obvezna neispunjena polja", "English": "Mandatory fields without values"},
    "FaultyValuesLabel": {"Hrvatski": "Neispravne vrijednosti polja", "English": "Invalid field values"},
    "InvalidItemLabel": {"Hrvatski": "Neispravni zapis", "English": "Invalid item"},
    "ErrorReportFixItemButton": {"Hrvatski": "Popravi zapis", "English": "Fix item"},
    "ErrorReportExcludeItemButton": {"Hrvatski": "Odbaci zapis", "English": "Exclude item"},
    "ErrorReportIncludeItemButton": {"Hrvatski": "Ignoriraj i uključi u zbirku", "English": "Ignore and include"},
    "ErrorReportContextItemButton": {"Hrvatski": "Kontekst", "English": "Context"},
    "CSVRemove": {"Hrvatski": "Ukloni", "English": "Remove"},
    "ErrorReportFixAll": {"Hrvatski": "Popravi sve", "English": "Fix all"},
    "ErrorReportIncludeAll": {"Hrvatski": "Ignoriraj sve i uključi u zbirku", "English": "Ignore all and include"},
    "ErrorReportExcludeAll": {"Hrvatski": "Odbaci sve", "English": "Exclude all"},
    "NoModelsLabel": {"Hrvatski": 'Nema definiranih modela.<br>Bez definiranih modela nije moguće izraditi bibliograifju.<br>Kako bi definirali vlastiti model, odaberite opciju "Izrada novog modela" u izborniku "Modeli"'},
    "NewCitationStyleWindowTitle": {"Hrvatski": "Izrada novog citatnog stila", "English": "New citation style"},
    "NewStyleNamePlaceholder": {"Hrvatski": "Naziv novog citatnog stila", "English": "New citation style name"},
    "AddFieldToStyleButton": {"Hrvatski": "Dodaj u stil", "English": "Add to style"},
    "DelimiterLabel": {"Hrvatski": "Graničnik za polja s više vrijednosti", "English": "Delimiter for fields with multiple values"},
    "LastDelimiterLabel": {"Hrvatski": "Posljednji graničnik za polja s više vrijednosti", "English": "Last delimiter for fields with multiple values"},
    "SaveCitationStyleButton": {"Hrvatski": "Spremi citatni stil", "English": "Save citation style"},
    "BIBTEXMapperWindow": {"Hrvatski": "Mapiranje BibTeX-a", "English": "BibTeX mapping"},
    "BIBFieldMappingLabel": {"Hrvatski": "Mapiranje BibTeX polja", "English": "BibTeX field mappings"},
    "BIBTypeMappingLabel": {"Hrvatski": "Mapiranje BibTeX vrsti publikacija", "English": "BibTeX publication type mappings"},
    "BIBAddField": {"Hrvatski": "Dodaj polje", "English": "Add field"},
    "BIBAddType": {"Hrvatski": "Dodaj vrstu publikacije", "English": "Add publication type"},
    "BIBSaveChanges": {"Hrvatski": "Spremi promjene", "English": "Spremi promjene"},
    "BIBMapAllToOneType": {"Hrvatski": "Mapiraj sve zapise u jednu vrstu publikacije", "English": "Map all items to one type of publication"},
    "BIBRemoveButton": {"Hrvatski": "Ukloni", "English": "Remove"},
    "BIBField": {"Hrvatski": "BibTeX polje", "English": "BibTeX Field"},
    "FilterWindowTitle": {"Hrvatski": "Filtriranje zbirke", "English": "Collection filtering"},
    "BIBType": {"Hrvatski": "BibTeX vrsta publikacije", "English": "BibTeX Type"},
    "FilterAddFilter": {"Hrvatski": "Dodaj filter", "English": "Add filter"},
    "RemoveFilters": {"Hrvatski": "Ukloni sve filtere", "English": "Remove all filters"},
    "FilterApply": {"Hrvatski": "Primjeni", "English": "Apply"},
    "ExecuteButton": {"Hrvatski": "Izvrši", "English": "Execute"},
    "ApplyToAllItems": {"Hrvatski": "Primjeni na sve zapise", "English": "Apply to all items"},
    "ApplyToSelectedItems": {"Hrvatski": "Primjeni na označene zapise", "English": "Apply to selected items"},
    "CaseChangeLabel": {"Hrvatski": "Promjena velikih i malih slova", "English": "Case change"},
    "CaseChangeSentenceCase": {"Hrvatski": "Prvo slovo prve riječi veliko", "English": "Sentence case"},
    "CaseChangeTitleCase": {"Hrvatski": "Prvo Slovo Svake Riječi Veliko", "English": "Title Case"},
    "CaseChangeALLCAPS": {"Hrvatski": "SVA SLOVA VELIKA", "English": "ALL UPPERCASE"},
    "CaseChangeAllLowercase": {"Hrvatski": "sva slova mala", "English": "all lowercase"},
    "PrepareItemsWindowTitle": {"Hrvatski": "Priprema zapisa", "English": "Prepare items"},
    "InversionFunctionLabel": {"Hrvatski": "Inverzija prema nizu znakova", "English": "Inversion by string"},
    "InversionFunctionInverseByPlaceholder": {"Hrvatski": "Niz znakova za inverziju", "English": "String to inverse by"},
    "SplitFunctionLabel": {"Hrvatski": "Raščlanjivanje prema nizu znakova", "English": "Split by string"},
    "SplitByTextPlaceholder": {"Hrvatski": "Niz znakova za raščlanjivanje", "English": "String to split by"},
    "ItemPrepReportWindowTitle": {"Hrvatski": "Izvještaj o promjenama u zbirci", "English": "Changes in collection report"},
    "PrepareItemsWindowDoReport": {"Hrvatski": "Izvještaj o promjenama u zbirci", "English": "Report on changes in collection"},
    "PrepReportNoChangesMade": {"Hrvatski": "Nema promjena u zbirci", "English": "No changes in collection"},
    "ReplaceFromItemLabel": {"Hrvatski": "Zamjena niza znakova u vrijednosti", "English": "String replacement in values"},
    "ReplaceFromItemPlaceholder": {"Hrvatski": "Niz znakova za zamjenu", "English": "String to replace"},
    "ReplaceWith": {"Hrvatski": "Zamjeni sa", "English": "Replace with"},
    "CaseFunctionLabel": {"Hrvatski": "Promjena velikih i malih slova", "English": "Letter case change"},
    "CaseUpper": {"Hrvatski": "SVA SLOVA VELIKA", "English": "UPPERCASE"},
    "CaseLower": {"Hrvatski": "sva slova mala", "English": "lowercase"},
    "CaseSentence": {"Hrvatski": "Rečenični stil", "English": "Sentence case"},
    "CaseTitle": {"Hrvatski": "Stil Naslova", "English": "Title Case"},
    "SystemTrayExit": {"Hrvatski": "Zatvori Azurio", "English": "Exit Azurio"},
    "AchievementUnlocked": {"Hrvatski": "Otključano postignuće", "English": "Achievement unlocked"},
    "FirstModelAchievement": {"Hrvatski": "Moj prvi model", "English": "My first model"},
    "FirstTrashAchievement": {"Hrvatski": "Provjeri smeće!", "English": "Check the trash!"},
    "UNIMARCMapperWindow": {"Hrvatski": "MARC mapiranje", "English": "MARC mapping"},
    "UNIMARCFieldLabel": {"Hrvatski": "Mapiranje MARC potpolja", "English": "MARC fields mapping"},
    "UNIMARCTypeLabel": {"Hrvatski": "Mapiranje MARC vrsti publikacija", "English": "MARC publication types mapping"},
    "UNIMARCAddFieldButton": {"Hrvatski": "Dodaj polje", "English": "Add field"},
    "UNIMARCAddTypeButton": {"Hrvatski": "Dodaj vrstu publikacije", "English": "Add publication type"},
    "UNIMARCOneTypeCheckbox": {"Hrvatski": "Mapiraj sve zapise u jednu vrstu publikacije", "English": "Map all items to one publication type"},
    "UNIMARCSaveChangesButton": {"Hrvatski": "Spremi promjene", "English": "Save changes"},
    "UNIMARCField": {"Hrvatski": "MARC potpolje", "English": "MARC field"},
    "UNIMARCRemove": {"Hrvatski": "Ukloni", "English": "Remove"},
    "UNIMARCTypePlaceholder": {"Hrvatski": "MARC kod za vrstu publikacije", "English": "MARC publication type code"},
    "SubstringFunctionLabel": {"Hrvatski": "Substring", "English": "Substring"},
    "PermaSaveCollectionWindowTitle": {"Hrvatski": "Trajno spremi zbirku", "English": "Permanently save the collection"},
    "PermaSaveNamePlaceholder": {"Hrvatski": "Ime za zbirku", "English": "Collection name"},
    "PermaSaveExistsWarning": {"Hrvatski": "Zbirka s tim imenom već postoji", "English": "Collection already exists"},
    "PermaSaveButton": {"Hrvatski": "Spremi", "English": "Save"},
    "PermaOverwriteBox": {"Hrvatski": "Zamjeni s novom zbirkom", "English": "Overwrite"},
    "OpenExistingCollectionWindow": {"Hrvatski": "Otvori postojeći zbirku", "English": "Open existing collection"},
    "OpenColColName": {"Hrvatski": "Ime zbirke", "English": "Collection name"},
    "OpenColBinCount": {"Hrvatski": "Zapisa u košu za smeće", "English": "Items in recycle bin"},
    "OpenColSelectedCount": {"Hrvatski": "Označenih zapisa", "English": "Selected items"},
    "OpenColModel": {"Hrvatski": "Model", "English": "Model"},
    "OpenColTime": {"Hrvatski": "Spremljeno", "English": "Save datetime"},
    "OpenColItemsCount": {"Hrvatski": "Broj zapisa", "English": "No. of items"},
    "OpenColButton": {"Hrvatski": "Otvori", "English": "Open"},
    "RemoveColButton": {"Hrvatski": "Izbriši", "English": "Delete"},
    "AddFilterButton": {"Hrvatski": "Dodaj filter", "English": "Add filter"},
    "RemoveFiltersButtons": {"Hrvatski": "Ukloni sve filtere", "English": "Remove all filters"},
    "ApplyFilters": {"Hrvatski": "Primjeni filtriranje", "English": "Apply filters"},
    "IntFilter+": {"Hrvatski": "veći od", "English": "more than"},
    "IntFilter-": {"Hrvatski": "manji od", "English": "less than"},
    "IntFilter=": {"Hrvatski": "jednako", "English": "equal to"},
    "StrFilter+": {"Hrvatski": "sadrži", "English": "contains"},
    "StrFilter-": {"Hrvatski": "ne sadrži", "English": "does not contain"},
    "StrFilter=": {"Hrvatski": "je", "English": "is"},
    "FilterParam": {"Hrvatski": "Parametar", "English": "Parameter"},
    "FilterAnd": {"Hrvatski": "i", "English": "and"},
    "FilterIf": {"Hrvatski": "Ako", "English": "If"},
    "CitationStyleName": {"Hrvatski": "Naziv stila navođenja", "English": "Citation style name"},
    "CitationStyleAddToSyntax": {"Hrvatski": "Dodaj u sintaksu", "English": "Add to syntax"},
    "CitationStyleSyntaxBoxPlaceholder": {"Hrvatski": "Sintaksa stila navođenja", "English": "Citation style syntax"},
    "CitationStylePreviewBoxPlaceholder": {"Hrvatski": "Predprikaz sintakse (prvi zapis u zbirci)", "English": "Citation style preview (first item in collection)"},
    "CitationStyleMultipleDelimiterLabel": {"Hrvatski": "Graničnik za polja s više vrijednosti", "English": "Multiple values delimiter"},
    "CitationStyleLastDelimiterLabel": {"Hrvatski": "Posljednji graničnik za polja s više vrijednosti", "English": "Last delimiter in multiple values"},
    "CitationStyleSave": {"Hrvatski": "Spremi stil navođenja", "English": "Save citation style"},
    "APACitationStyleWindow": {"Hrvatski": "APA mapiranje", "English": "APA mapping"},
    "APAFieldLabel": {"Hrvatski": "Mapiranje APA polja", "English": "APA field mappings"},
    "APATypeLabel": {"Hrvatski": "Mapiranje APA vrsti publikacija", "English": "APA publication type mappings"},
    "APAAddField": {"Hrvatski": "Dodaj polje", "English": "Add field"},
    "APAAddType": {"Hrvatski": "Dodaj vrstu publikacije", "English": "Add publication type"},
    "APARemove": {"Hrvatski": "Ukloni", "English": "Remove"},
    "APASaveChanges": {"Hrvatski": "Spremi promjene", "English": "Save changes"},
    "MainMenuBibliography": {"Hrvatski": "Bibliografija", "English": "Bibliography"},
    "NoCollectionWarning": {"Hrvatski": "Zbirka nije instancirana", "English": "Collection not instanced"},
    "NoItemsInCollectionWarning": {"Hrvatski": "Zbirka ne sadrži nijedan zapis", "English": "No items in collection"},
    "BibliographyManager": {"Hrvatski": "Upravljanje bibliografijom", "English": "Bibliography manager"},
    "BibliographyGenerateButton": {"Hrvatski": "Generiraj bibliografiju", "English": "Generate bibliography"},
    "BibliographyExportButton": {"Hrvatski": "Izvoz bibliografije", "English": "Export bibliography"},
    "BiblNumbering": {"Hrvatski": "Numeriranje", "English": "Numbering"},
    "BiblNoNumbering": {"Hrvatski": "Bez numeriranja", "English": "No numbering"},
    "BiblGlobalNumbering": {"Hrvatski": "Globalno numeriranje", "English": "Global numbering"},
    "BiblLocalNumbering": {"Hrvatski": "Lokalno numeriranje", "English": "Local numbering"},
    "NewCitationStylePreviewError": {"Hrvatski": "Pogreška u predprikazu. Pogrešno napisana sintaksa ili nema dostupnih zapisa u zbirci ili zbirka ne odgovara modelu citatnog stila ili zbirka ne postoji.", "English": "Preview error. Wrong syntax or no items in collection or model mismatch or no collection at all."},
    "DefaultStyle": {"Hrvatski": "zadani stil", "English": "default style"},
    "EditItemWindowTitle": {"Hrvatski": "Uređivanje zapisa", "English": "Item editing"},
    "EditExecuteButton": {"Hrvatski": "Spremi promjene", "English": "Save changes"},
    "ContextWindowTitle": {"Hrvatski": "Kontekst", "English": "Context"},
    "ContextNoData": {"Hrvatski": "Nema podataka", "English": "No data"},
    "SaveBibliography": {"Hrvatski": "Izvoz bibliografije", "English": "Bibliography export"},
    "NoCollection": {"Hrvatski": "Zbirka nije instancirana", "English": "Collection doesn't exist"},
    "CollectionPermaSaved": {"Hrvatski": "Zbirka uspješno spremljena", "English": "Collection saved successfully"},
    "ModelCreated": {"Hrvatski": "Model uspješno izrađen", "English": "Model created successfully"},
    "StyleSaved": {"Hrvatski": "Citatni stil uspješno spremljen", "English": "Citation style saved successfully"},
    "ValidateCollection": {"Hrvatski": "Provjera valjanosti zbirke", "English": "Validate collection"},
    "CollectionValid": {"Hrvatski": "Zbirka je valjana", "English": "Collection valid"},
    "ColBack": {"Hrvatski": "Poništi", "English": "Undo"},
    "ColRedo": {"Hrvatski": "Ponovi", "English": "Redo"}

}

with open('translations.json', 'w') as fp:
    json.dump(translations, fp)